export const ADD_COMPLAIN_REQUEST = "ADD_COMPLAIN_REQUEST";
export const ADD_COMPLAIN_SUCCESS = "ADD_COMPLAIN_SUCCESS";
export const ADD_COMPLAIN_FAILURE = "ADD_COMPLAIN_FAILURE";

export const GET_ALLCOMPLAIN_REQUEST = "GET_ALLCOMPLAIN_REQUEST";
export const GET_ALLCOMPLAIN_SUCCESS = "GET_ALLCOMPLAIN_SUCCESS";
export const GET_ALLCOMPLAIN_FAILURE = "GET_ALLCOMPLAIN_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const GET_ALLPRODUCT_REQUEST = "GET_ALLPRODUCT_REQUEST";
export const GET_ALLPRODUCT_SUCCESS = "GET_ALLPRODUCT_SUCCESS";
export const GET_ALLPRODUCT_FAILURE = "GET_ALLPRODUCT_FAILURE";

